import { existsSync, readFileSync, statSync } from "node:fs"
import { join } from "node:path"

import type { StarlightUserConfig } from "@astrojs/starlight/types"

/**
 * What the content directory currently holds, read at config load.
 *
 * The docs tree is generated by `comprehensive-codebase-understanding` and synced in by
 * `scripts/sync-ccu.mjs`, so which category directories exist is a fact about the last sync rather
 * than a constant. Starlight throws on an `autogenerate` directory with no files, so a hardcoded
 * sidebar fails the build for a category the generator has not written yet — which is a build failure
 * about the *site* for a gap in the *tree*. The sidebar is therefore derived from disk.
 *
 * The same read answers a second question. `citation-links.ts` turns a citation into an intra-site
 * link only when the tree page it names is actually published; anything else becomes a repo
 * permalink. Deriving "published" from the sync manifest rather than from the presence of a file
 * under the tree keeps a citation into an unpublished sibling — `docs/CONTRACT.md` — off a route that
 * does not exist.
 */

/** The content collection directory, relative to the Astro project root. */
export const COLLECTION_ROOT = "src/content/docs"

/** The manifest `sync-ccu.mjs` writes, naming every path it owns in the collection. */
const SYNC_MANIFEST = ".ccu-sync.json"

/**
 * ccu's reading order for the six category directories.
 *
 * Starlight computes a group's sort weight as the minimum `sidebar.order` of the routes it contains,
 * and `sync-ccu.mjs` stamps that rank onto every page, so this table only has to name the LABEL and
 * the shape. The order itself travels in the frontmatter.
 */
const CATEGORIES: ReadonlyArray<{
  readonly directory: string
  readonly label: string
  /** Named subgroups, for a category ccu nests one level deeper. */
  readonly subgroups?: ReadonlyArray<{ readonly directory: string; readonly label: string }>
}> = [
  { directory: "architecture", label: "Architecture" },
  { directory: "reference", label: "Reference" },
  { directory: "behavior", label: "Behavior" },
  { directory: "analysis", label: "Analysis" },
  {
    directory: "diagrams",
    label: "Diagrams",
    /*
     * ccu nests diagrams one level deeper than every other category, so autogenerating `diagrams` as
     * one directory produces a subgroup labelled "architecture" beside the top-level Architecture
     * group — two sidebar entries with one name, one of them holding a class diagram. Each subgroup
     * is therefore named here.
     */
    subgroups: [
      { directory: "diagrams/architecture", label: "Components" },
      { directory: "diagrams/structural", label: "Structure" },
      { directory: "diagrams/behavioral", label: "Sequences" }
    ]
  },
  { directory: "insights", label: "Insights" }
]

/** The tree's own landing page, published at `/readme/`. */
const TREE_LANDING = "README.md"

const isDirectory = (path: string): boolean => {
  try {
    return statSync(path).isDirectory()
  } catch {
    return false
  }
}

/** The frontmatter `title` `sync-ccu.mjs` stamped onto a synced page, when the page exists. */
const stampedTitle = (root: string, treePath: string): string | undefined => {
  const path = join(root, treePath)
  if (!existsSync(path)) return undefined
  const raw = /^---\r?\n[\s\S]*?^title:[ \t]*"((?:[^"\\]|\\.)*)"[ \t]*$/m.exec(
    readFileSync(path, "utf8")
  )?.[1]
  return raw === undefined ? undefined : raw.replaceAll('\\"', '"').replaceAll("\\\\", "\\")
}

/**
 * Every path in the collection that the last sync wrote, as tree-relative slash-separated paths.
 *
 * An empty set is the honest answer before the first sync: nothing is published, so every citation
 * takes the permalink branch.
 */
export const syncedTreePaths = (projectRoot: string): ReadonlySet<string> => {
  try {
    const parsed: unknown = JSON.parse(
      readFileSync(join(projectRoot, COLLECTION_ROOT, SYNC_MANIFEST), "utf8")
    )
    const files = (parsed as { files?: unknown }).files
    if (!Array.isArray(files)) return new Set()
    return new Set(files.filter((file): file is string => typeof file === "string"))
  } catch {
    return new Set()
  }
}

/**
 * The sidebar: the agent page pinned first, then whichever ccu categories exist.
 *
 * "For agents" is first because an agent arriving at the site should not have to find it, and because
 * placement is the only lever on whether guidance is read at all.
 */
export const sidebar = (projectRoot: string): StarlightUserConfig["sidebar"] => {
  const root = join(projectRoot, COLLECTION_ROOT)
  const items: NonNullable<StarlightUserConfig["sidebar"]> = [
    { label: "For agents", link: "/agents/" }
  ]

  const treeTitle = stampedTitle(root, TREE_LANDING)
  if (treeTitle !== undefined) items.push({ label: treeTitle, link: "/readme/" })

  for (const category of CATEGORIES) {
    if (category.subgroups === undefined) {
      if (!isDirectory(join(root, category.directory))) continue
      items.push({
        label: category.label,
        collapsed: category.directory !== "architecture",
        items: [{ autogenerate: { directory: category.directory } }]
      })
      continue
    }
    // `collapsed` does not cascade, so each nested group states its own.
    const present = category.subgroups.filter((sub) => isDirectory(join(root, sub.directory)))
    if (present.length === 0) continue
    items.push({
      label: category.label,
      collapsed: true,
      items: present.map((sub) => ({
        label: sub.label,
        collapsed: true,
        items: [{ autogenerate: { directory: sub.directory } }]
      }))
    })
  }

  return items
}
